language: java

jdk:
  - openjdk8

install: true

script: mvn install

before_install:
 - mvn clean

after_success:
 - mvn clean cobertura:cobertura coveralls:report

branches:
 only:
    - master

notifications:
  slack: cheese-dev:JXKSTVY4wHsMPbJi2uoKtyxs
  email: false